/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.ticketing;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.lang.reflect.Field;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.util.*;

/**
 *
 * @author user
 */
public class BookSeat extends javax.swing.JFrame implements ActionListener{
    
    private String startingPoint;
    private String destination;
    private String busNo;
    private String busType;
    private String departureTime;
    private String arrivalTime;
    private String fare;
    private String selectedSeat = "";
    private Date selectedDate;
  
Map<String, Set<String>> bookedSeatsByDate = new HashMap<>();
   
    
    public BookSeat() {
        initComponents();
        Traveldate.addPropertyChangeListener("date", evt -> {
    refreshSeatAvailability();});
         bindSeatButtons();

    }  
    
      
        
    public BookSeat(String startingPoint, String destination, String busNo, String busType, String departureTime, String arrivalTime, String fare) {
    initComponents();
    this.startingPoint=startingPoint;
     this.destination=destination;
     this.busNo = busNo;
        this.busType = busType;
        this.departureTime = departureTime;
        this.arrivalTime = arrivalTime;
        this.fare = fare;
    
    
    
    jLabel2.setText("Bus No.: "+busNo); 
    jLabel3.setText("Bus Type.: "+busType);
    jLabel4.setText(departureTime+"   --> "+arrivalTime);
   
    jLabel6.setText("Fare: P"+fare);
    jLabel7.setText(startingPoint +"   --> "+ destination);
   
}
    private void handleSeatSelection(String seatNumber, JButton seatButton) {
    if (Traveldate.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Please choose a travel date first.");
        return;
    }

    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    String date = df.format(Traveldate.getDate());

    bookedSeatsByDate.putIfAbsent(date, new HashSet<>());
    bookedSeatsByDate.get(date).add(seatNumber);
    
    selectedSeat = seatNumber;
    seatButton.setEnabled(false); // Disable the button after selection

    JOptionPane.showConfirmDialog(this, "Selected Seat is " + selectedSeat + "\nTravel Date is " + date);
    jLabel49.setText("Your Seat: " + selectedSeat);
}
  private void bindSeatButtons() {
    for (int i = 1; i <= 38; i++) {
        String seatId = "S" + i;
        JButton seatButton;

        try {
            // Use reflection to get each seat button by name
            Field field = this.getClass().getDeclaredField("seat" + i);
            field.setAccessible(true);
            seatButton = (JButton) field.get(this);

            JButton finalSeatButton = seatButton;
            seatButton.addActionListener(e -> handleSeatSelection(seatId, finalSeatButton));

        } catch (Exception ex) {
            ex.printStackTrace(); // Optional: show which one failed
        }
    }
}
  private void refreshSeatAvailability() {
    if (Traveldate.getDate() == null) return;

    String date = new SimpleDateFormat("yyyy-MM-dd").format(Traveldate.getDate());
    Set<String> bookedSeats = bookedSeatsByDate.getOrDefault(date, new HashSet<>());

    for (int i = 1; i <= 38; i++) {
        try {
            Field field = this.getClass().getDeclaredField("seat" + i);
            field.setAccessible(true);
            JButton seatButton = (JButton) field.get(this);
            String seatId = "S" + i;

            seatButton.setEnabled(!bookedSeats.contains(seatId));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        conbtn = new javax.swing.JButton();
        seat11 = new javax.swing.JButton();
        seat12 = new javax.swing.JButton();
        seat13 = new javax.swing.JButton();
        seat14 = new javax.swing.JButton();
        seat15 = new javax.swing.JButton();
        seat16 = new javax.swing.JButton();
        seat17 = new javax.swing.JButton();
        seat18 = new javax.swing.JButton();
        seat19 = new javax.swing.JButton();
        seat20 = new javax.swing.JButton();
        seat21 = new javax.swing.JButton();
        seat22 = new javax.swing.JButton();
        seat23 = new javax.swing.JButton();
        seat37 = new javax.swing.JButton();
        seat24 = new javax.swing.JButton();
        seat25 = new javax.swing.JButton();
        seat26 = new javax.swing.JButton();
        seat27 = new javax.swing.JButton();
        seat28 = new javax.swing.JButton();
        seat29 = new javax.swing.JButton();
        seat30 = new javax.swing.JButton();
        seat31 = new javax.swing.JButton();
        seat32 = new javax.swing.JButton();
        seat33 = new javax.swing.JButton();
        seat1 = new javax.swing.JButton();
        seat2 = new javax.swing.JButton();
        seat3 = new javax.swing.JButton();
        seat4 = new javax.swing.JButton();
        seat5 = new javax.swing.JButton();
        seat6 = new javax.swing.JButton();
        seat7 = new javax.swing.JButton();
        seat8 = new javax.swing.JButton();
        seat9 = new javax.swing.JButton();
        seat10 = new javax.swing.JButton();
        seat38 = new javax.swing.JButton();
        seat34 = new javax.swing.JButton();
        seat35 = new javax.swing.JButton();
        seat36 = new javax.swing.JButton();
        seat39 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bus No.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bus Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fare:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 95, -1, 30));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, -1, 20));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Travel:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 22, -1, 10));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Travel Time:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 62, -1, 20));

        jLabel1.setBackground(new java.awt.Color(15, 42, 29));
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 140));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Your Seat", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Californian FB", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 0, 0));
        jLabel49.setText("Your Seat:");
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        conbtn.setBackground(new java.awt.Color(15, 42, 29));
        conbtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        conbtn.setForeground(new java.awt.Color(255, 255, 255));
        conbtn.setText("CONTINUE");
        conbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black));
        conbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conbtnActionPerformed(evt);
            }
        });
        jPanel2.add(conbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 100, 35));

        seat11.setBackground(new java.awt.Color(0, 102, 51));
        seat11.setText("11");
        seat11.setToolTipText("");
        seat11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat11ActionPerformed(evt);
            }
        });
        jPanel2.add(seat11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 50, -1));

        seat12.setBackground(new java.awt.Color(0, 102, 51));
        seat12.setText("12");
        seat12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat12ActionPerformed(evt);
            }
        });
        jPanel2.add(seat12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 50, -1));

        seat13.setBackground(new java.awt.Color(0, 102, 51));
        seat13.setText("13");
        seat13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat13ActionPerformed(evt);
            }
        });
        jPanel2.add(seat13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 50, -1));

        seat14.setBackground(new java.awt.Color(0, 102, 51));
        seat14.setText("14");
        seat14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat14ActionPerformed(evt);
            }
        });
        jPanel2.add(seat14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 50, -1));

        seat15.setBackground(new java.awt.Color(0, 102, 51));
        seat15.setText("15");
        seat15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat15ActionPerformed(evt);
            }
        });
        jPanel2.add(seat15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 50, -1));

        seat16.setBackground(new java.awt.Color(0, 102, 51));
        seat16.setText("16");
        seat16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat16ActionPerformed(evt);
            }
        });
        jPanel2.add(seat16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 50, -1));

        seat17.setBackground(new java.awt.Color(0, 102, 51));
        seat17.setText("17");
        seat17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat17ActionPerformed(evt);
            }
        });
        jPanel2.add(seat17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 50, -1));

        seat18.setBackground(new java.awt.Color(0, 102, 51));
        seat18.setText("18");
        seat18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat18ActionPerformed(evt);
            }
        });
        jPanel2.add(seat18, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 50, -1));

        seat19.setBackground(new java.awt.Color(0, 102, 51));
        seat19.setText("19");
        seat19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat19ActionPerformed(evt);
            }
        });
        jPanel2.add(seat19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 50, -1));

        seat20.setBackground(new java.awt.Color(0, 102, 51));
        seat20.setText("20");
        seat20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat20ActionPerformed(evt);
            }
        });
        jPanel2.add(seat20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 50, -1));

        seat21.setBackground(new java.awt.Color(0, 102, 51));
        seat21.setText("21");
        seat21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat21ActionPerformed(evt);
            }
        });
        jPanel2.add(seat21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 50, -1));

        seat22.setBackground(new java.awt.Color(0, 102, 51));
        seat22.setText("22");
        seat22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat22ActionPerformed(evt);
            }
        });
        jPanel2.add(seat22, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 50, -1));

        seat23.setBackground(new java.awt.Color(0, 102, 51));
        seat23.setText("23");
        seat23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat23ActionPerformed(evt);
            }
        });
        jPanel2.add(seat23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 50, -1));

        seat37.setBackground(new java.awt.Color(0, 102, 51));
        seat37.setText("37");
        seat37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat37ActionPerformed(evt);
            }
        });
        jPanel2.add(seat37, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 50, -1));

        seat24.setBackground(new java.awt.Color(0, 102, 51));
        seat24.setText("24");
        seat24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat24ActionPerformed(evt);
            }
        });
        jPanel2.add(seat24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 50, -1));

        seat25.setBackground(new java.awt.Color(0, 102, 51));
        seat25.setText("25");
        seat25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat25ActionPerformed(evt);
            }
        });
        jPanel2.add(seat25, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 50, -1));

        seat26.setBackground(new java.awt.Color(0, 102, 51));
        seat26.setText("26");
        seat26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat26ActionPerformed(evt);
            }
        });
        jPanel2.add(seat26, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 50, -1));

        seat27.setBackground(new java.awt.Color(0, 102, 51));
        seat27.setText("27");
        seat27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat27ActionPerformed(evt);
            }
        });
        jPanel2.add(seat27, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 50, -1));

        seat28.setBackground(new java.awt.Color(0, 102, 51));
        seat28.setText("28");
        seat28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat28ActionPerformed(evt);
            }
        });
        jPanel2.add(seat28, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 50, -1));

        seat29.setBackground(new java.awt.Color(0, 102, 51));
        seat29.setText("29");
        seat29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat29ActionPerformed(evt);
            }
        });
        jPanel2.add(seat29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 50, -1));

        seat30.setBackground(new java.awt.Color(0, 102, 51));
        seat30.setText("30");
        seat30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat30ActionPerformed(evt);
            }
        });
        jPanel2.add(seat30, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 50, -1));

        seat31.setBackground(new java.awt.Color(0, 102, 51));
        seat31.setText("31");
        seat31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat31ActionPerformed(evt);
            }
        });
        jPanel2.add(seat31, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 50, -1));

        seat32.setBackground(new java.awt.Color(0, 102, 51));
        seat32.setText("32");
        seat32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat32ActionPerformed(evt);
            }
        });
        jPanel2.add(seat32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 50, -1));

        seat33.setBackground(new java.awt.Color(0, 102, 51));
        seat33.setText("33");
        seat33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat33ActionPerformed(evt);
            }
        });
        jPanel2.add(seat33, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 50, -1));

        seat1.setBackground(new java.awt.Color(0, 102, 51));
        seat1.setText("1");
        seat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat1ActionPerformed(evt);
            }
        });
        jPanel2.add(seat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 50, -1));

        seat2.setBackground(new java.awt.Color(0, 102, 51));
        seat2.setText("2");
        seat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat2ActionPerformed(evt);
            }
        });
        jPanel2.add(seat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, -1));

        seat3.setBackground(new java.awt.Color(0, 102, 51));
        seat3.setText("3");
        seat3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat3ActionPerformed(evt);
            }
        });
        jPanel2.add(seat3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 50, -1));

        seat4.setBackground(new java.awt.Color(0, 102, 51));
        seat4.setText("4");
        seat4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat4ActionPerformed(evt);
            }
        });
        jPanel2.add(seat4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 50, -1));

        seat5.setBackground(new java.awt.Color(0, 102, 51));
        seat5.setText("5");
        seat5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat5ActionPerformed(evt);
            }
        });
        jPanel2.add(seat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 50, -1));

        seat6.setBackground(new java.awt.Color(0, 102, 51));
        seat6.setText("6");
        seat6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat6ActionPerformed(evt);
            }
        });
        jPanel2.add(seat6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 50, -1));

        seat7.setBackground(new java.awt.Color(0, 102, 51));
        seat7.setText("7");
        seat7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat7ActionPerformed(evt);
            }
        });
        jPanel2.add(seat7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 50, -1));

        seat8.setBackground(new java.awt.Color(0, 102, 51));
        seat8.setText("8");
        seat8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat8ActionPerformed(evt);
            }
        });
        jPanel2.add(seat8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 50, -1));

        seat9.setBackground(new java.awt.Color(0, 102, 51));
        seat9.setText("9");
        seat9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat9ActionPerformed(evt);
            }
        });
        jPanel2.add(seat9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 50, -1));

        seat10.setBackground(new java.awt.Color(0, 102, 51));
        seat10.setText("10");
        seat10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat10ActionPerformed(evt);
            }
        });
        jPanel2.add(seat10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 50, -1));

        seat38.setBackground(new java.awt.Color(0, 102, 51));
        seat38.setText("38");
        seat38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat38ActionPerformed(evt);
            }
        });
        jPanel2.add(seat38, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 50, -1));

        seat34.setBackground(new java.awt.Color(0, 102, 51));
        seat34.setText("34");
        seat34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat34ActionPerformed(evt);
            }
        });
        jPanel2.add(seat34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 50, -1));

        seat35.setBackground(new java.awt.Color(0, 102, 51));
        seat35.setText("35");
        seat35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat35ActionPerformed(evt);
            }
        });
        jPanel2.add(seat35, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 50, -1));

        seat36.setBackground(new java.awt.Color(0, 102, 51));
        seat36.setText("36");
        seat36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat36ActionPerformed(evt);
            }
        });
        jPanel2.add(seat36, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 50, -1));

        seat39.setBackground(new java.awt.Color(0, 102, 51));
        seat39.setText("39");
        seat39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seat39ActionPerformed(evt);
            }
        });
        jPanel2.add(seat39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, 50, -1));

        jButton1.setBackground(new java.awt.Color(207, 212, 210));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(15, 42, 29));
        jButton1.setText("CANCEL");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 42, 29), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 100, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seat4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat4ActionPerformed
       handleSeatSelection("S4", seat4);
    }//GEN-LAST:event_seat4ActionPerformed

    private void seat38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat38ActionPerformed
         handleSeatSelection("S38", seat38);
    }//GEN-LAST:event_seat38ActionPerformed

    private void seat37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat37ActionPerformed
      handleSeatSelection("S37", seat37);
    }//GEN-LAST:event_seat37ActionPerformed

    private void seat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat1ActionPerformed
         handleSeatSelection("S1", seat1);
    }//GEN-LAST:event_seat1ActionPerformed

    private void seat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat2ActionPerformed
         handleSeatSelection("S2", seat2);
   
    }//GEN-LAST:event_seat2ActionPerformed

    private void seat3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat3ActionPerformed
       handleSeatSelection("S3", seat3);
    }//GEN-LAST:event_seat3ActionPerformed

    private void seat5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat5ActionPerformed
         handleSeatSelection("S5", seat5);
    }//GEN-LAST:event_seat5ActionPerformed

    private void seat6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat6ActionPerformed
      handleSeatSelection("S6", seat6);
    }//GEN-LAST:event_seat6ActionPerformed

    private void seat7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat7ActionPerformed
        handleSeatSelection("S7", seat7);
    }//GEN-LAST:event_seat7ActionPerformed

    private void seat8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat8ActionPerformed
         handleSeatSelection("S8", seat8);
    }//GEN-LAST:event_seat8ActionPerformed

    private void seat9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat9ActionPerformed
       handleSeatSelection("S9", seat9);
    }//GEN-LAST:event_seat9ActionPerformed

    private void seat10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat10ActionPerformed
        handleSeatSelection("S10", seat10);
    }//GEN-LAST:event_seat10ActionPerformed

    private void seat11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat11ActionPerformed
      handleSeatSelection("S1", seat1);
    }//GEN-LAST:event_seat11ActionPerformed

    private void seat12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat12ActionPerformed
        handleSeatSelection("S12", seat12);
    }//GEN-LAST:event_seat12ActionPerformed

    private void seat13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat13ActionPerformed
       handleSeatSelection("S13", seat13);
    }//GEN-LAST:event_seat13ActionPerformed

    private void seat14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat14ActionPerformed
         handleSeatSelection("S14", seat14);
    }//GEN-LAST:event_seat14ActionPerformed

    private void seat15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat15ActionPerformed
       handleSeatSelection("S15", seat15);
    }//GEN-LAST:event_seat15ActionPerformed

    private void seat16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat16ActionPerformed
        handleSeatSelection("S16", seat16);
    }//GEN-LAST:event_seat16ActionPerformed

    private void seat17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat17ActionPerformed
        handleSeatSelection("S17", seat17);
    }//GEN-LAST:event_seat17ActionPerformed

    private void seat18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat18ActionPerformed
       handleSeatSelection("S18", seat18);
    }//GEN-LAST:event_seat18ActionPerformed

    private void seat19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat19ActionPerformed
        handleSeatSelection("S19", seat19);
    }//GEN-LAST:event_seat19ActionPerformed

    private void seat20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat20ActionPerformed
       handleSeatSelection("S20", seat20);
    }//GEN-LAST:event_seat20ActionPerformed

    private void seat21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat21ActionPerformed
        handleSeatSelection("S21", seat21);
    }//GEN-LAST:event_seat21ActionPerformed

    private void seat22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat22ActionPerformed
        handleSeatSelection("S22", seat22);
    }//GEN-LAST:event_seat22ActionPerformed

    private void seat23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat23ActionPerformed
        handleSeatSelection("S23", seat23);
    }//GEN-LAST:event_seat23ActionPerformed

    private void seat24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat24ActionPerformed
        handleSeatSelection("S24", seat24);
    }//GEN-LAST:event_seat24ActionPerformed

    private void seat25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat25ActionPerformed
       handleSeatSelection("S25", seat25);
    }//GEN-LAST:event_seat25ActionPerformed

    private void seat26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat26ActionPerformed
        handleSeatSelection("S26", seat26);
    }//GEN-LAST:event_seat26ActionPerformed

    private void seat27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat27ActionPerformed
        handleSeatSelection("S27", seat27);
    }//GEN-LAST:event_seat27ActionPerformed

    private void seat28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat28ActionPerformed
        handleSeatSelection("S28", seat28);
    }//GEN-LAST:event_seat28ActionPerformed

    private void seat29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat29ActionPerformed
         handleSeatSelection("S29", seat29);
    }//GEN-LAST:event_seat29ActionPerformed

    private void seat30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat30ActionPerformed
       handleSeatSelection("S30", seat30);
    }//GEN-LAST:event_seat30ActionPerformed

    private void seat31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat31ActionPerformed
         handleSeatSelection("S31", seat31);
    }//GEN-LAST:event_seat31ActionPerformed

    private void seat32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat32ActionPerformed
         handleSeatSelection("S32", seat32);
    }//GEN-LAST:event_seat32ActionPerformed

    private void seat33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat33ActionPerformed
        handleSeatSelection("S33", seat33);
    }//GEN-LAST:event_seat33ActionPerformed

    private void seat34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat34ActionPerformed
        handleSeatSelection("S34", seat34);
    }//GEN-LAST:event_seat34ActionPerformed

    private void seat35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat35ActionPerformed
        handleSeatSelection("S35", seat35);
    }//GEN-LAST:event_seat35ActionPerformed

    private void seat36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat36ActionPerformed
        handleSeatSelection("S36", seat36);
    }//GEN-LAST:event_seat36ActionPerformed

    private void seat39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seat39ActionPerformed
        handleSeatSelection("S39", seat39);
    }//GEN-LAST:event_seat39ActionPerformed

    public String getSelectedSeat() {
    return selectedSeat;
}

public Date getSelectedDate() {
    return Traveldate.getDate(); 
}

public String getStartingPoint() {
    return startingPoint;
}

public String getDestination() {
    return destination;
}

public String getBusNo() {
    return busNo;
}

public String getBusType() {
    return busType;
}

public String getDepartureTime() {
    return departureTime;
}

public String getArrivalTime() {
    return arrivalTime;
}

public String getFare() {
    return fare;
}
    private void conbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conbtnActionPerformed
        if (getSelectedSeat().isEmpty() || getSelectedDate() == null) {
        JOptionPane.showMessageDialog(this, "Please select both seat and date before continuing.");
        return;
    }

    
    SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    String Date = df.format(getSelectedDate());

   
    TicketView view = new TicketView(
        getStartingPoint(),
        getDestination(),
        getBusNo(),
        getBusType(),
        getDepartureTime(),
        getArrivalTime(),
        getFare(),
        getSelectedSeat(),
        Date
    );

    view.setVisible(true);
    view.setLocationRelativeTo(null);
    dispose(); 
    }//GEN-LAST:event_conbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     PassengerCA selectBus= new PassengerCA();
     selectBus.setVisible(true);
     selectBus.show();
     selectBus.setLocationRelativeTo(null);
     dispose();
     
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookSeat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookSeat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton conbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton seat1;
    private javax.swing.JButton seat10;
    private javax.swing.JButton seat11;
    private javax.swing.JButton seat12;
    private javax.swing.JButton seat13;
    private javax.swing.JButton seat14;
    private javax.swing.JButton seat15;
    private javax.swing.JButton seat16;
    private javax.swing.JButton seat17;
    private javax.swing.JButton seat18;
    private javax.swing.JButton seat19;
    private javax.swing.JButton seat2;
    private javax.swing.JButton seat20;
    private javax.swing.JButton seat21;
    private javax.swing.JButton seat22;
    private javax.swing.JButton seat23;
    private javax.swing.JButton seat24;
    private javax.swing.JButton seat25;
    private javax.swing.JButton seat26;
    private javax.swing.JButton seat27;
    private javax.swing.JButton seat28;
    private javax.swing.JButton seat29;
    private javax.swing.JButton seat3;
    private javax.swing.JButton seat30;
    private javax.swing.JButton seat31;
    private javax.swing.JButton seat32;
    private javax.swing.JButton seat33;
    private javax.swing.JButton seat34;
    private javax.swing.JButton seat35;
    private javax.swing.JButton seat36;
    private javax.swing.JButton seat37;
    private javax.swing.JButton seat38;
    private javax.swing.JButton seat39;
    private javax.swing.JButton seat4;
    private javax.swing.JButton seat5;
    private javax.swing.JButton seat6;
    private javax.swing.JButton seat7;
    private javax.swing.JButton seat8;
    private javax.swing.JButton seat9;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
      
        
    }}
