/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.ticketing;


import bus.ticketing.ManageFrame;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class LOgIn extends javax.swing.JFrame {

    /**
     * Creates new form LOgIn
     */
    public LOgIn() {
        initComponents();
        sqlconnect();
    }
    PreparedStatement ps;
    Connection connect;
    ResultSet result;
   
  
    public void sqlconnect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost/busticketing","root","");
             System.out.print("Connected");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        Logintab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        psEmail = new javax.swing.JTextField();
        psPass = new javax.swing.JPasswordField();
        UserLoginbtn = new javax.swing.JButton();
        Pcreateacc = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label5 = new java.awt.Label();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        MngEmail = new javax.swing.JTextField();
        MngPass = new javax.swing.JPasswordField();
        adminlogin = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        panel1 = new java.awt.Panel();

        jTextField1.setText("jTextField1");

        jPasswordField2.setText("jPasswordField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(207, 212, 210));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("LOG IN");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 103, 30));

        psEmail.setBackground(new java.awt.Color(255, 255, 255));
        psEmail.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        psEmail.setForeground(new java.awt.Color(153, 153, 153));
        psEmail.setText("enter email address");
        psEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                psEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                psEmailFocusLost(evt);
            }
        });
        psEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psEmailActionPerformed(evt);
            }
        });
        jPanel3.add(psEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 250, 30));

        psPass.setBackground(new java.awt.Color(255, 255, 255));
        psPass.setForeground(new java.awt.Color(153, 153, 153));
        psPass.setText("Enter Password");
        psPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                psPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                psPassFocusLost(evt);
            }
        });
        psPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psPassActionPerformed(evt);
            }
        });
        jPanel3.add(psPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 250, 30));

        UserLoginbtn.setBackground(new java.awt.Color(15, 42, 29));
        UserLoginbtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        UserLoginbtn.setForeground(new java.awt.Color(255, 255, 255));
        UserLoginbtn.setText("LOG IN");
        UserLoginbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0)));
        UserLoginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLoginbtnActionPerformed(evt);
            }
        });
        jPanel3.add(UserLoginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 250, 35));

        Pcreateacc.setBackground(new java.awt.Color(207, 212, 210));
        Pcreateacc.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        Pcreateacc.setForeground(new java.awt.Color(0, 0, 0));
        Pcreateacc.setText("Create Account");
        Pcreateacc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(15, 42, 29), 1, true));
        Pcreateacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcreateaccActionPerformed(evt);
            }
        });
        jPanel3.add(Pcreateacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 250, 35));

        jCheckBox1.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setText("show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        label1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label1.setText("Email");
        jPanel3.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));
        label1.getAccessibleContext().setAccessibleName("Name");

        label2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label2.setText("Password");
        jPanel3.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        Logintab.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(15, 42, 29));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(207, 212, 210));
        jButton1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Manage");
        jButton1.setToolTipText("");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 60));

        jButton2.setBackground(new java.awt.Color(207, 212, 210));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Book Ticket");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(153, 153, 153)));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 260, 60));

        jButton3.setBackground(new java.awt.Color(15, 42, 29));
        jButton3.setFont(new java.awt.Font("sansserif", 1, 10)); // NOI18N
        jButton3.setText("About Us");
        jButton3.setBorder(null);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 90, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Welcome to");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, 30));

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Book your Travel Ticket in a Minute");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 50));

        label5.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        label5.setForeground(new java.awt.Color(255, 255, 255));
        label5.setPreferredSize(new java.awt.Dimension(135, 34));
        label5.setText("E - GoTicket");
        jPanel4.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 240, 40));

        Logintab.addTab("tab3", jPanel4);

        jPanel1.setBackground(new java.awt.Color(207, 212, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOG IN");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 85, 35));

        MngEmail.setBackground(new java.awt.Color(255, 255, 255));
        MngEmail.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        MngEmail.setForeground(new java.awt.Color(153, 153, 153));
        MngEmail.setText("enter email address");
        MngEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MngEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MngEmailFocusLost(evt);
            }
        });
        MngEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MngEmailActionPerformed(evt);
            }
        });
        jPanel1.add(MngEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 250, 30));

        MngPass.setBackground(new java.awt.Color(255, 255, 255));
        MngPass.setForeground(new java.awt.Color(153, 153, 153));
        MngPass.setText("Enter Password");
        MngPass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                MngPassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                MngPassFocusLost(evt);
            }
        });
        MngPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MngPassActionPerformed(evt);
            }
        });
        jPanel1.add(MngPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 250, 30));

        adminlogin.setBackground(new java.awt.Color(15, 42, 29));
        adminlogin.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        adminlogin.setForeground(new java.awt.Color(255, 255, 255));
        adminlogin.setText("LOG IN");
        adminlogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 0, 0)));
        adminlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminloginActionPerformed(evt);
            }
        });
        jPanel1.add(adminlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 250, 35));

        jCheckBox2.setBackground(new java.awt.Color(207, 212, 210));
        jCheckBox2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox2.setText("show password");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        label3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label3.setText("Email");
        jPanel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        label4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        label4.setText("Password");
        jPanel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));
        jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        Logintab.addTab("tab1", jPanel1);

        getContentPane().add(Logintab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Logintab.setSelectedIndex(1);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
              Logintab.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        jButton1.setBackground(new Color(0,102,51));
        jButton2.setBackground(Color.white);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         jButton2.setBackground(new Color(0,102,51));
        jButton1.setBackground(Color.white);
    }//GEN-LAST:event_jButton2MouseClicked

    private void psPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psPassActionPerformed

    private void adminloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminloginActionPerformed
   

    String username = MngEmail.getText();
    String password = String.valueOf(MngPass.getPassword());
    try {
     
        if (connect != null) {  
            ps = connect.prepareStatement("SELECT * FROM `admin_table` WHERE `Email` = ? AND `Pass_Assigned`= ?");
            
            ps.setString(1, username);
            ps.setString(2, password);
            result = ps.executeQuery();
             
            if (result.next()) {
                JOptionPane.showMessageDialog(this, "Log In Successfully");
                String adminEmail = MngEmail.getText().trim();
                 ManageFrame passad= new ManageFrame(adminEmail);
                ManageFrame manage= new ManageFrame();
                dispose();
                manage.setVisible(true);
                manage.show();
                manage.setLocationRelativeTo(null);
            } else {
                JOptionPane.showMessageDialog(this, "No Existing Account");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }      
         
    }//GEN-LAST:event_adminloginActionPerformed
    
    
    private void UserLoginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginbtnActionPerformed
      

    String username = psEmail.getText();
    String password = String.valueOf(psPass.getPassword());
    try {
     
        if (connect != null) {  
            ps = connect.prepareStatement("SELECT * FROM `passenger_table` WHERE `Passenger_Email` = ? AND `Passenger_Password`= ?");
            
            ps.setString(1, username);
            ps.setString(2, password);
            result = ps.executeQuery();
             
            if (result.next()) {
                JOptionPane.showMessageDialog(this, "Log In Successfully");
                PassengerCA passenger= new PassengerCA();
                dispose();
                passenger.setVisible(true);
                passenger.show();
                passenger.setLocationRelativeTo(null);
               
            } else {
                JOptionPane.showMessageDialog(this, "No Existing Account");
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }      
         
                                             
    }//GEN-LAST:event_UserLoginbtnActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
         Logintab.setSelectedIndex(0);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton1.setBackground(Color.white);
        jButton2.setBackground(Color.white);
        jButton3.setBackground(new Color(0,102,51));
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PcreateaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcreateaccActionPerformed
        SignUp signup= new SignUp();
        signup.setVisible(true);
        signup.show();
        signup.setLocationRelativeTo(null);
    }//GEN-LAST:event_PcreateaccActionPerformed

    private void psEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psEmailFocusGained
        if(psEmail.getText().equals("Enter Email")){
            psEmail.setText("");
            psEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_psEmailFocusGained

    private void psEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psEmailFocusLost
       if(psEmail.getText().equals("")){
            psEmail.setText("Enter Email");
            psEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_psEmailFocusLost

    private void psPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psPassFocusGained
       if(psPass.getText().equals("Enter Password")){
            psPass.setText("");
          
            psPass.setForeground(new Color(0,0,0));
            
            psPass.setEchoChar('*');
           
          
       }
    }//GEN-LAST:event_psPassFocusGained

    private void psPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psPassFocusLost
          if(psPass.getText().equals("")){
            psPass.setText("Enter Password");
            psPass.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_psPassFocusLost

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
       if(jCheckBox1.isSelected()){
           psPass.setEchoChar((char)0);
       }else{
             psPass.setEchoChar('*');
       }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void MngEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MngEmailFocusGained
        if(MngEmail.getText().equals("Enter Email")){
            MngEmail.setText("");
            MngEmail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_MngEmailFocusGained

    private void MngEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MngEmailFocusLost
         if(MngEmail.getText().equals("")){
            MngEmail.setText("Enter Email");
            MngEmail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_MngEmailFocusLost

    private void MngPassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MngPassFocusGained
      if(MngPass.getText().equals("Enter Password")){
            MngPass.setText("");
          
            MngPass.setForeground(new Color(0,0,0));
            
            MngPass.setEchoChar('*');
      }
    }//GEN-LAST:event_MngPassFocusGained

    private void MngPassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_MngPassFocusLost
        if(MngPass.getText().equals("")){
            MngPass.setText("Enter Password");
          
            MngPass.setForeground(new Color(153,153,153));
            
            MngPass.setEchoChar('*');
        }
    }//GEN-LAST:event_MngPassFocusLost

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
       if(jCheckBox2.isSelected()){
           MngPass.setEchoChar((char)0);
       }else{
             MngPass.setEchoChar('*');
       }
       
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void MngEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MngEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MngEmailActionPerformed

    private void MngPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MngPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MngPassActionPerformed

    private void psEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOgIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOgIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOgIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOgIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOgIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Logintab;
    private javax.swing.JTextField MngEmail;
    private javax.swing.JPasswordField MngPass;
    private javax.swing.JButton Pcreateacc;
    private javax.swing.JButton UserLoginbtn;
    private javax.swing.JButton adminlogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Panel panel1;
    private javax.swing.JTextField psEmail;
    private javax.swing.JPasswordField psPass;
    // End of variables declaration//GEN-END:variables
}
