/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.ticketing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.Statement; 

/**
 *
 * @author user
 */
public class TicketView extends javax.swing.JFrame {
        private String startingPoint, destination, busNo, busType, departureTime, arrivalTime, fare, seat, date;
        Random rand = new Random();
        
    /**
     * Creates new form TicketView
     */
    public TicketView() {
        initComponents();
        sqlconnect();
       
    }
 PreparedStatement ps;
    Connection connect;
    ResultSet result;
  
     
    public void sqlconnect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost/busticketing","root","");
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public TicketView(String startingPoint, String destination, String busNo, String busType,String departureTime, String arrivalTime, String fare,String seat, String date){
        initComponents();
        this.startingPoint = startingPoint;
    this.destination = destination;
    this.busNo = busNo;
    this.busType = busType;
    this.departureTime = departureTime;
    this.arrivalTime = arrivalTime;
    this.fare = fare;
    this.seat = seat;
    this.date = date;
        
        
        
        jLabel9.setText(busNo);
        jLabel10.setText(busType);
        jLabel11.setText(startingPoint+" -> "+destination);
        jLabel12.setText(departureTime+" -> "+arrivalTime);
        jLabel13.setText(date);
        jLabel14.setText(seat);
        jLabel15.setText(fare);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        confirmName = new javax.swing.JTextField();
        confirmtickbtn = new javax.swing.JButton();
        canceltickbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(207, 212, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Confirm Your Booking");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Bus No.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Bus Type:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Travel :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Travel Date:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Travel Time:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Seat: ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total Amount:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel11.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, -1, 20));

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        jLabel13.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("jLabel13");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, -1));

        jLabel14.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("jLabel14");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel15.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("jLabel15");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Name:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        confirmName.setBackground(new java.awt.Color(204, 204, 204));
        confirmName.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        confirmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmNameActionPerformed(evt);
            }
        });
        jPanel1.add(confirmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 260, 30));

        confirmtickbtn.setBackground(new java.awt.Color(15, 42, 29));
        confirmtickbtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        confirmtickbtn.setText("Confirm");
        confirmtickbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 0, 0)));
        confirmtickbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmtickbtnActionPerformed(evt);
            }
        });
        jPanel1.add(confirmtickbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 200, 40));

        canceltickbtn.setBackground(new java.awt.Color(207, 212, 210));
        canceltickbtn.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        canceltickbtn.setForeground(new java.awt.Color(0, 0, 0));
        canceltickbtn.setText("Cancel");
        canceltickbtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(15, 42, 29)));
        canceltickbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canceltickbtnActionPerformed(evt);
            }
        });
        jPanel1.add(canceltickbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmtickbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmtickbtnActionPerformed
          int passengerId = 100000 + rand.nextInt(900000); 
          int discount=0;
        if(confirmName.getText().isEmpty()){
              JOptionPane.showMessageDialog(this, "Please Enter Name to Confirm Booking!");
          }
        try {
            connect=DriverManager.getConnection("jdbc:mysql://localhost/busticketing","root","");
          ps = connect.prepareStatement(
    "INSERT INTO ticket_table (Passengers_ID, Passenger_Name, Bus_ID, Seat_No, StartingPoint, Destination, Date, Discount, Total_amount) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
    Statement.RETURN_GENERATED_KEYS
);
        ps.setInt(1, passengerId);        
        ps.setString(2, confirmName.getText());          
        ps.setString(3, busNo);        
        ps.setString(4, seat);    
        ps.setString(5, startingPoint);      
        ps.setString(6, destination); 
        SimpleDateFormat dFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date utilDate = dFormat.parse(date);
        java.sql.Date Date = new java.sql.Date(utilDate.getTime());

        ps.setDate(7, Date); 
        ps.setInt(8, discount);   
         int totalAmount = Integer.parseInt(fare);
        ps.setInt(9,totalAmount );        

         int k = ps.executeUpdate();

    result = ps.getGeneratedKeys();
      if (result.next()) {
    int ticketId = result.getInt(1);
    
        JOptionPane.showMessageDialog(this, " Ticket Added Successfully!");
        Ticketfinal finalTicket = new Ticketfinal(ticketId,passengerId,confirmName.getText(),busNo,seat,startingPoint,destination,departureTime,arrivalTime,Date,totalAmount);
            finalTicket.setVisible(true);
            finalTicket.setLocationRelativeTo(null);
            dispose();
    }    
        } catch (SQLException ex) {
            Logger.getLogger(TicketView.class.getName()).log(Level.SEVERE, null, ex);
        }   catch (ParseException ex) {
                Logger.getLogger(TicketView.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_confirmtickbtnActionPerformed

    private void canceltickbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canceltickbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canceltickbtnActionPerformed

    private void confirmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicketView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton canceltickbtn;
    private javax.swing.JTextField confirmName;
    private javax.swing.JButton confirmtickbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
