/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bus.ticketing;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }
     PreparedStatement ps;
    Connection connect;
    ResultSet result;
     ResultSetMetaData rsm;
     DefaultTableModel tmodel; 
    public void sqlconnect(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
             connect=DriverManager.getConnection("jdbc:mysql://localhost/busticketing","root","");
          
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PFname = new javax.swing.JTextField();
        PLname = new javax.swing.JTextField();
        Page = new javax.swing.JTextField();
        Pcontact = new javax.swing.JTextField();
        Pemail = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Ppass = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("E - GoTicket");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        PFname.setForeground(new java.awt.Color(153, 153, 153));
        PFname.setText("Enter Firstname");
        PFname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PFnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PFnameFocusLost(evt);
            }
        });
        jPanel1.add(PFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 270, -1));

        PLname.setForeground(new java.awt.Color(153, 153, 153));
        PLname.setText("Enter Lastname");
        PLname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PLnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PLnameFocusLost(evt);
            }
        });
        PLname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PLnameActionPerformed(evt);
            }
        });
        jPanel1.add(PLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 270, -1));

        Page.setForeground(new java.awt.Color(153, 153, 153));
        Page.setText("Enter Age");
        Page.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PageFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PageFocusLost(evt);
            }
        });
        jPanel1.add(Page, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 270, -1));

        Pcontact.setForeground(new java.awt.Color(153, 153, 153));
        Pcontact.setText("Contact");
        Pcontact.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PcontactFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PcontactFocusLost(evt);
            }
        });
        jPanel1.add(Pcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 270, -1));

        Pemail.setForeground(new java.awt.Color(153, 153, 153));
        Pemail.setText("Enter Email");
        Pemail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PemailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PemailFocusLost(evt);
            }
        });
        jPanel1.add(Pemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 270, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 51));
        jButton1.setText("SIGN UP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 428, 110, 40));

        Ppass.setForeground(new java.awt.Color(153, 153, 153));
        Ppass.setText("Password");
        Ppass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PpassFocusLost(evt);
            }
        });
        jPanel1.add(Ppass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 270, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bus/ticketing/pics/left-arrow.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 450, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PLnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PLnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PLnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
    connect = DriverManager.getConnection("jdbc:mysql://localhost/busticketing","root","");

   
    if ( 
    PFname.getText().isEmpty() || 
    PLname.getText().isEmpty() || 
    Page.getText().isEmpty() || 
    Pcontact.getText().isEmpty() || 
    Pemail.getText().isEmpty() || 
    Ppass.getText().isEmpty()) { 
    JOptionPane.showMessageDialog(this, "Please fill all fields!");
    return;
}

    String query = "INSERT INTO `passenger_table`( `firstname`, `lastname`, `age`, `contact`, `Passenger_Email`, `Passenger_Password`) VALUES (?,?,?,?,?,?)";
    ps = connect.prepareStatement(query);
    ps.setString(1, PFname.getText());
     ps.setString(2, PLname.getText());
   ps.setInt(3, Integer.parseInt(Page.getText())); 
     ps.setString(4, Pcontact.getText());
      ps.setString(5, Pemail.getText());
       ps.setString(6, Ppass.getText());
  
 
    
    int k = ps.executeUpdate();

    if(k == 1) {
        JOptionPane.showMessageDialog(this, " Sign Up Successfully!");
       dispose();
         
       
    } else {
        JOptionPane.showMessageDialog(this, "Adding Failed!");
    }

} catch (SQLException ex) {
    Logger.getLogger(ManageFrame.class.getName()).log(Level.SEVERE, "SQL Error Code: " + ex.getErrorCode() + " - " + ex.getMessage(), ex);
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PFnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PFnameFocusGained
        if(PFname.getText().equals("Enter Firstname")){
            PFname.setText("");
            PFname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PFnameFocusGained

    private void PFnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PFnameFocusLost
       if(PFname.getText().equals("")){
            PFname.setText("Enter Firstname");
            PFname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PFnameFocusLost

    private void PLnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PLnameFocusGained
        if(PLname.getText().equals("Enter Lastname")){
            PLname.setText("");
            PLname.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PLnameFocusGained

    private void PLnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PLnameFocusLost
         if(PLname.getText().equals("")){
            PLname.setText("Enter Lastname");
            PLname.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PLnameFocusLost

    private void PageFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PageFocusGained
        if(Page.getText().equals("Enter Age")){
            Page.setText("");
            Page.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PageFocusGained

    private void PageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PageFocusLost
       if(Page.getText().equals("")){
            Page.setText("Enter Age");
            Page.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PageFocusLost

    private void PcontactFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PcontactFocusGained
        if(Pcontact.getText().equals("Contact")){
            Pcontact.setText("");
            Pcontact.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PcontactFocusGained

    private void PcontactFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PcontactFocusLost
       if(Pcontact.getText().equals("")){
            Pcontact.setText("Contact");
            Pcontact.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PcontactFocusLost

    private void PemailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PemailFocusGained
         if(Pemail.getText().equals("Enter Email")){
            Pemail.setText("");
            Pemail.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PemailFocusGained

    private void PemailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PemailFocusLost
          if(Pemail.getText().equals("")){
            Pemail.setText("Enter Email");
            Pemail.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PemailFocusLost

    private void PpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PpassFocusGained
          if(Ppass.getText().equals("Password")){
            Ppass.setText("");
            Ppass.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_PpassFocusGained

    private void PpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PpassFocusLost
       if(Ppass.getText().equals("")){
            Ppass.setText("Password");
            Ppass.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_PpassFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
        dispose();
      
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PFname;
    private javax.swing.JTextField PLname;
    private javax.swing.JTextField Page;
    private javax.swing.JTextField Pcontact;
    private javax.swing.JTextField Pemail;
    private javax.swing.JTextField Ppass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
